### ISSUE TITLE
Code license

### ISSUE THREAD

**Issue by sieukrem** [walkert/go-evp#1]
I would like to use your EVP implementation, but I don't know if allowed!.

Would you please add a license to the repository, so that it can be evaluated automatically in respect to OSS clearing procedures.

**Comment by walkert** [comment]
Hi. I've added a license as well as a couple of commits that were sitting un-pushed. These are breaking changes but the library will still work as before. I'd be interested to hear where you're using this! Thanks.

**Comment by sieukrem** [comment]
Hi, thanks for the fast solving of the issue and the library!

> I'd be interested to hear where you're using this! Thanks.

Currently I am not allowed to talk about the software we are building, but in principle these are two services in the cloud talking to each other. One is written in Nodejs and another in Go.  Your port of evp is the only one which allowed me to decrypt the data encrypted by Nodejs application.

Thanks also for the permissive license ;-)!

**Comment by walkert** [comment]
That's great - you're welcome! I actually wrote this in the first place so I could decrypt some data written using `openssl`. Happy coding.
